# Generated by Django 4.0.4 on 2022-05-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Student name')),
                ('studentId', models.PositiveBigIntegerField(default=' ', unique=True, verbose_name='Student Id ')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('level', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('birth', models.DateField(verbose_name='Birth day')),
                ('phoneNumber', models.PositiveBigIntegerField(default=' ', unique=True, verbose_name='Phone number')),
                ('gender', models.CharField(max_length=30, verbose_name='Gender')),
            ],
        ),
    ]
