# Generated by Django 4.0.4 on 2022-05-17 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_add_department_alter_add_birth_alter_add_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='department',
        ),
        migrations.AlterField(
            model_name='add',
            name='birth',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Birth day'),
        ),
        migrations.AlterField(
            model_name='add',
            name='gender',
            field=models.CharField(default='', max_length=30, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='add',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='add',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='add',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Student name'),
        ),
    ]
