# Generated by Django 4.0.4 on 2022-05-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_add_department_alter_add_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='id',
        ),
        migrations.AlterField(
            model_name='add',
            name='phoneNumber',
            field=models.PositiveBigIntegerField(default=' ', verbose_name='Phone Number '),
        ),
        migrations.AlterField(
            model_name='add',
            name='studentId',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Student id'),
        ),
    ]
