# Generated by Django 4.0.4 on 2022-05-17 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_add_id_alter_add_phonenumber_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add',
            new_name='Sadd',
        ),
    ]
