# Generated by Django 4.0.4 on 2022-05-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_add_sadd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sadd',
        ),
    ]
