# Generated by Django 4.0.4 on 2022-05-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_add_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='birthday',
            field=models.DateField(),
        ),
    ]
